export const SET_CHART_PROPERTIES = 'SET_CHART_PROPERTIES';
export const SET_SELECTED_PROPERTIES = 'SET_SELECTED_PROPERTIES';
export const SET_TITLE = 'SET_TITLE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_ADAPTER_RESULT = 'SET_ADAPTER_RESULT';
export const SET_IS_LONG_POLLING = 'SET_IS_LONG_POLLING';
