export const SET_CHART_PROPERTIES = 'SET_CHART_PROPERTIES';
export const SET_SELECTED_PROPERTIES = 'SET_SELECTED_PROPERTIES';
export const SET_TITLE = 'SET_TITLE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_ADAPTER_RESULT = 'SET_ADAPTER_RESULT';
export const SET_IS_LONG_POLLING = 'SET_IS_LONG_POLLING';
export const SET_IS_INITIAL_CALL = 'SET_IS_INITIAL_CALL';
export const SET_ADT_HIERARCHY_NODES = 'SET_ADT_HIERARCHY_NODES';
export const SET_ADT_HIERARCHY_NODE_PROPERTIES =
    'SET_ADT_HIERARCHY_NODE_PROPERTIES';
export const SET_ADT_HIERARCHY_SELECTED_TWIN_ID =
    'SET_ADT_HIERARCHY_SELECTED_TWIN_ID';
export const SET_ADT_HIERARCHY_SEARCH = 'SET_ADT_HIERARCHY_SEARCH';
export const SET_TWIN_LOOKUP_STATUS = 'SET_TWIN_LOOKUP_STATUS';
export const SET_SELECTED_BLOB_CONTAINER_URL =
    'SET_SELECTED_BLOB_CONTAINER_URL';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_ERROR_CALLBACK = 'SET_ERROR_CALLBACK';
export const SET_SELECTED_SCENE = 'SET_SELECTED_SCENE';
export const SET_CURRENT_STEP = 'SET_CURRENT_STEP';
export const SET_ADT_SCENE_CONFIG = 'SET_ADT_SCENE_CONFIG';
export const SET_ADT_SCENE_BUILDER_ELEMENTS = 'SET_ADT_SCENE_BUILDER_ELEMENTS';
export const SET_ADT_SCENE_BUILDER_BEHAVIORS =
    'SET_ADT_SCENE_BUILDER_BEHAVIORS';
export const SET_ADT_SCENE_BUILDER_SELECTED_ELEMENT =
    'SET_ADT_SCENE_BUILDER_SELECTED_ELEMENT';
export const SET_ADT_SCENE_ELEMENT_SELECTED_OBJECT_IDS =
    'SET_ADT_SCENE_ELEMENT_SELECTED_OBJECT_IDS';
export const SET_ADT_SCENE_BUILDER_MODE = 'SET_ADT_SCENE_BUILDER_MODE';
export const SET_ADT_SCENE_PAGE_MODE = 'SET_ADT_SCENE_PAGE_MODE';
export const SET_OAT_DELETED_MODEL_ID = 'SET_OAT_DELETED_MODEL_ID';
export const SET_OAT_EDITED_MODEL_NAME = 'SET_OAT_EDITED_MODEL_NAME';
export const SET_OAT_EDITED_MODEL_ID = 'SET_OAT_EDITED_MODEL_ID';
export const SET_OAT_IMPORT_MODELS = 'SET_OAT_IMPORT_MODELS';
export const SET_OAT_IS_JSON_UPLOADER_OPEN = 'SET_OAT_IS_JSON_UPLOADER_OPEN';
export const SET_OAT_ELEMENTS = 'SET_OAT_ELEMENTS';
export const SET_OAT_SELECTED_MODEL_ID = 'SET_OAT_SELECTED_MODEL_ID';
export const SET_OAT_PROPERTY_EDITOR_MODEL = 'SET_OAT_PROPERTY_EDITOR_MODEL';
export const SET_OAT_TEMPLATES = 'SET_OAT_TEMPLATES';
export const SET_OAT_TEMPLATES_ACTIVE = 'SET_OAT_TEMPLATES_ACTIVE';
