export const OAT_HEADER_HEIGHT = 76;
export const OAT_FLOATING_CONTROL_BUTTON_SIZE = 32;
export const OAT_FLOATING_CONTROL_LEFT_OFFSET = 30;

export const CONTROLS_BOTTOM_OFFSET = 30;
export const CONTROLS_Z_INDEX = 6;
export const LOADING_Z_INDEX = CONTROLS_Z_INDEX + 1;
